name: github action 실행 테스트
on:
  push:
    branches:
      - main
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: 다중 run
        run: |
          echo "Good"
          echo "Morning"
      - name: 변수 값 보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
      - name: github secret
        run: |
          echo ${{secrets.MY_NAME}}
          pwd
          whoami
